### ISSUE TITLE
Revisar Pruebas 

### ISSUE THREAD

**Issue by larry852** [entregascontinuas/loencontre.co#3]
Revisar pruebas realizadas y mejorarlas

**Comment by AlvaroHernandezM** [comment]
1- Volver a ejecutar prueba unitaria número 1 Backend: páginación; ya que su tiempo de ejecución no es coherente. (5,98 s)
2- Reemplazar o eliminar prueba unitaria 1 de Frontend: inicialización de controlador principal
3- Búsqueda de herramientas adicionales para pruebas de sistema

**Comment by andresmauriciogomezr** [comment]
Pruebas unitarias al día
