### ISSUE TITLE
Herramientas para revisión de codigo  - Calidad

### ISSUE THREAD

**Issue by larry852** [entregascontinuas/loencontre.co#7]
Buscar herramientas de revision de código para la aplicacion.

**Comment by AlvaroHernandezM** [comment]
Realizar el anáisis de código estático primero sin Travis, haciendo uso de un plugin o herramienta de escaneo directamente con el repositorio, de:

- [ ] Backend PHP

- [ ] Frontend JS

- [ ] Frontend JS
