### ISSUE TITLE
Extracción de Miembros 

### ISSUE THREAD

**Issue by AlvaroHernandezM** [entregascontinuas/loencontre.co#77]
La extracción de miembros de grupo de FB y almacenamiento en local no debería realizarse cuando la persona vaya a publicar ya que tarda demasiado tiempo y no es razonable. (Van 10 minutos y nada que termina)

**Opcion 1** que exista un script que extraiga todos los miembros del grupo (en un primer momento solo es necesario tener el nombre y el id del usuario en Facebook) y se almacenen no de forma local si no en una tabla de nuestro servidor con el fin de que se comparen las distintas combinaciones seleccionadas con los nombres de esos miembros.

De todas las coincidencias encontradas en el momento de la publicación extraer solo las fotos publicas del perfil de usuario donde se identifica un rostro para compararlo con la foto del carné. (este tiempo de extracción si sería inevitable si se hace de esta manera pero se reduce porque son mucho menos los candidtos)

**Opcion 2** el script que se encargue de extraer tanto nombre, id de usuario y fotos publicas donde se se deberá identificar el rostro en las fotos y solo si existe uno se almacenará. 

Dichos script se deberán ejecutar diariamente o un lapso de tiempo razonable para mantener la base de datos actualizada y la persona que vaya a realizar una publicación no deba esperar tanto si no el tiempo de búsqueda y comparación de rostros.... Evitando extraer miembros y llenar una base de datos local.

Lo más seguro es que existan personas que quieran realizar una primera publicación y se detengan al ver que tarda mucho la primera publicación, pensando que así serán todas.

**Comment by larry852** [comment]
Issues identificado y resuelto, detalles Issue #70

**Comment by larry852** [comment]
Actualmente el tiempo de almacenamiento es menos de un minuto
